name: flex
channels:
  - conda-forge
  - defaults
dependencies:
  - gmsh
  - jax==0.5.0
  - jaxopt
  - numpy
  - pygmo
  - python==3.12
  - python-gmsh
  - trame
  - ipywidgets
  - scipy
  - scikit-learn
  - pyvista
  - typeguard
  - yaml
  - pygraphviz
  # - petsc4py
  - pip
  - pip:
      - git+https://github.com/cpml-au/dctkit
      - git+https://github.com/cpml-au/deap
      - "ray[default]"
      - pygmsh
      - tox
      - mygrad
      - tox-conda
      - pmlb
      - optuna
      - optuna-integration
      - sympy
